// The ONE place the Mac side knows which icon names exist. The device has its own copy
// in MacEmoji.h, generated by emoji2c.py - the two are separate languages and must be
// edited together; CLAUDE.md says so, because a name valid here and unknown there shows
// as no icon at all.
//
// Order matters only for the check script's first-name assertion; the wire carries the
// NAME, never an index, so adding to the middle of this list is safe.
//
// NOTE: this list is transcribed from firmware/deckhand_display/MacEmoji.h, not from the
// task brief - the brief's list still says "robot", but the generated header replaced it
// with "apple" (at 13px "robot" read as a cupcake). The two name tables can't read each
// other (one is Python, one is JS), so a divergence here would silently mean that name's
// icon never appears on the device.
export const MAC_EMOJI_NAMES = [
  "rocket", "moon", "star", "bolt", "fire", "leaf", "wave", "anchor",
  "crab", "laptop", "desktop", "cloud", "sun", "cat", "apple", "gear",
];

// env beats file: the plist is the provisioning path, and a value someone set
// deliberately must not be silently overridden by a click in the menu bar. An invalid
// value at either level is DROPPED rather than passed through, so the device falls back
// to the text tag instead of showing nothing at all.
export function resolveMacEmoji({ env, file } = {}) {
  const clean = (v) => String(v ?? "").trim().toLowerCase();
  for (const candidate of [clean(env), clean(file)]) {
    if (candidate && MAC_EMOJI_NAMES.includes(candidate)) return candidate;
  }
  return "";
}
