#!/usr/bin/env python3
"""
Convert the crab-walk animation frames into a C header for the firmware.

Input : the frames file - either a .swift with the base64 strings quoted, or
        a plain text file with ONE base64 PNG per line.
Output: ClawdCrab.h - N frames, 8-bit palette indices + an RGB565 palette.

The PNGs are RGBA with anti-aliased edges. The alpha is composited against the
UI background HERE, at build time, so the device stores opaque pixels only and
needs no per-pixel blending. Only ~66 distinct colours survive RGB565
quantisation, so an 8-bit index + palette is LOSSLESS and roughly half the size
of raw RGB565.

  python3 crab2c.py crab_frames.b64 > ClawdCrab.h
"""
import base64, re, struct, sys, zlib
from collections import Counter

BG = (0, 0, 0)          # COLOR_BG - what the alpha is composited against

def decode_png(b64):
    d = base64.b64decode(b64.strip())
    if d[:8] != b'\x89PNG\r\n\x1a\n':
        raise ValueError("not a PNG")
    pos, idat, ihdr = 8, b'', None
    while pos < len(d):
        ln  = struct.unpack('>I', d[pos:pos+4])[0]
        typ = d[pos+4:pos+8]
        if (zlib.crc32(d[pos+4:pos+8+ln]) & 0xffffffff) != struct.unpack('>I', d[pos+8+ln:pos+12+ln])[0]:
            raise ValueError(f"CRC mismatch in {typ.decode()} - data is corrupt")
        if   typ == b'IHDR': ihdr = d[pos+8:pos+8+ln]
        elif typ == b'IDAT': idat += d[pos+8:pos+8+ln]
        elif typ == b'IEND': break
        pos += 12 + ln
    w, h, bd, ct, _, _, il = struct.unpack('>IIBBBBB', ihdr)
    if (bd, ct, il) != (8, 6, 0):
        raise ValueError(f"expected 8-bit RGBA non-interlaced, got bd={bd} ct={ct} il={il}")
    raw, bpp = zlib.decompress(idat), 4
    rows, prev, i = [], bytearray(w*bpp), 0
    for _ in range(h):
        f = raw[i]; i += 1
        line = bytearray(raw[i:i+w*bpp]); i += w*bpp
        for x in range(len(line)):
            a = line[x-bpp] if x >= bpp else 0
            b = prev[x]
            c = prev[x-bpp] if x >= bpp else 0
            if   f == 1: line[x] = (line[x] + a) & 255
            elif f == 2: line[x] = (line[x] + b) & 255
            elif f == 3: line[x] = (line[x] + (a+b)//2) & 255
            elif f == 4:
                p = a + b - c
                pa, pb, pc = abs(p-a), abs(p-b), abs(p-c)
                line[x] = (line[x] + (a if (pa<=pb and pa<=pc) else b if pb<=pc else c)) & 255
        rows.append(bytes(line)); prev = line
    return w, h, rows

def to565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def main():
    # Accept the .swift source directly: pull out the quoted base64 strings.
    # Falling back to one-per-line keeps plain .b64 files working too, but this
    # means there is no separate extracted copy of the art to keep in sync.
    text = open(sys.argv[1]).read()
    quoted = re.findall(r'"([A-Za-z0-9+/=]{100,})"', text)
    lines = quoted if quoted else [l for l in text.split('\n') if l.strip()]
    frames, W, H = [], None, None
    for i, l in enumerate(lines):
        try:
            w, h, rows = decode_png(l)
        except Exception as e:
            sys.exit(f"frame {i+1}: {e}")
        if W is None: W, H = w, h
        elif (w, h) != (W, H): sys.exit(f"frame {i+1}: size {w}x{h} != {W}x{H}")
        px = []
        for r in rows:
            for x in range(w):
                R, G, B, A = r[x*4:x*4+4]
                # composite over the UI background so the device stores no alpha
                px.append(to565(*(c*A//255 + bgc*(255-A)//255 for c, bgc in zip((R, G, B), BG))))
        frames.append(px)

    hist = Counter(c for f in frames for c in f)
    palette = [c for c, _ in hist.most_common()]
    if len(palette) > 256:
        sys.exit(f"{len(palette)} colours - needs quantising to fit an 8-bit index")
    idx = {c: i for i, c in enumerate(palette)}

    n = len(frames)
    # Run-length encode each row (runs never cross a row, so the decoder just
    # tracks x/y). This is BOTH the storage format and the draw format: the
    # firmware turns each run straight into one fillRect, so nothing is
    # decompressed into RAM and the per-frame draw-call count drops ~3.5x.
    blobs = []
    for f in frames:
        out = bytearray()
        for y in range(H):
            row = f[y*W:(y+1)*W]
            i = 0
            while i < len(row):
                j = i
                while j + 1 < len(row) and row[j+1] == row[i] and (j - i + 1) < 255:
                    j += 1
                out += bytes((idx[row[i]], j - i + 1))
                i = j + 1
        blobs.append(bytes(out))
    offs, acc = [], 0
    for b in blobs:
        offs.append(acc); acc += len(b)
    offs.append(acc)

    print("// Generated by crab2c.py - do not edit by hand.")
    print(f"// Clawd crab-walk easter egg: {n} frames, {W}x{H}.")
    print("// Alpha was composited against COLOR_BG at build time (no blending on device).")
    print("// Stored RLE as (palette index, run length) pairs, runs never crossing a row -")
    print("// each run becomes ONE fillRect, so there is no decompression buffer and the")
    print("// draw-call count drops from W*H to the number of runs.")
    print("#pragma once")
    print("#include <pgmspace.h>")
    print(f"#define CRAB_FRAMES {n}")
    print(f"#define CRAB_W {W}")
    print(f"#define CRAB_H {H}")
    print(f"#define CRAB_COLORS {len(palette)}")
    print(f"const uint16_t CRAB_PAL[{len(palette)}] PROGMEM = {{", end="")
    print(",".join(f"0x{c:04X}" for c in palette), end="};\n")
    print(f"const uint16_t CRAB_OFF[{n+1}] PROGMEM = {{" + ",".join(str(o) for o in offs) + "};")
    print(f"const uint8_t CRAB_RLE[{acc}] PROGMEM = {{")
    for b in blobs:
        print("  " + ",".join(str(v) for v in b) + ",")
    print("};")

if __name__ == "__main__":
    main()
