#!/usr/bin/env python3
"""
Convert the Claude-spark animation frames into a C header for the firmware.

Input : the frames file - either a .swift with the base64 strings quoted, or
        a plain text file with ONE base64 PNG per line.
Output: ClaudeSpark.h - 8 frames at SIZE x SIZE, 2 bits per pixel.

The PNGs are 60x60 RGBA, pure black with 4 alpha levels, i.e. anti-aliased
MASKS. We keep only the alpha, box-filter down to SIZE, and quantise to 2 bits
(0 = transparent .. 3 = solid). The firmware tints them with the status colour,
so one copy serves any colour and the art costs SIZE*SIZE*2/8 bytes per frame.

  python3 spark2c.py frames.b64 > ClaudeSpark.h
"""
import base64, re, struct, sys, zlib

SIZE = 32   # 16 is unreadable, 24 marginal, 32 reads clearly and still fits the row

def decode_png(b64):
    d = base64.b64decode(b64.strip())
    if d[:8] != b'\x89PNG\r\n\x1a\n':
        raise ValueError("not a PNG")
    pos, idat, ihdr = 8, b'', None
    while pos < len(d):
        ln  = struct.unpack('>I', d[pos:pos+4])[0]
        typ = d[pos+4:pos+8]
        body = d[pos+8:pos+8+ln]
        crc = struct.unpack('>I', d[pos+8+ln:pos+12+ln])[0]
        if (zlib.crc32(d[pos+4:pos+8+ln]) & 0xffffffff) != crc:
            raise ValueError(f"CRC mismatch in {typ.decode()} chunk - data is corrupt")
        if typ == b'IHDR': ihdr = body
        elif typ == b'IDAT': idat += body
        elif typ == b'IEND': break
        pos += 12 + ln
    w, h, bd, ct, _, _, il = struct.unpack('>IIBBBBB', ihdr)
    if (bd, ct, il) != (8, 6, 0):
        raise ValueError(f"expected 8-bit RGBA non-interlaced, got bd={bd} ct={ct} il={il}")
    raw, bpp = zlib.decompress(idat), 4
    rows, prev, i = [], bytearray(w*bpp), 0
    for _ in range(h):                      # undo per-scanline filters
        f = raw[i]; i += 1
        line = bytearray(raw[i:i+w*bpp]); i += w*bpp
        for x in range(len(line)):
            a = line[x-bpp] if x >= bpp else 0
            b = prev[x]
            c = prev[x-bpp] if x >= bpp else 0
            if   f == 1: line[x] = (line[x] + a) & 255
            elif f == 2: line[x] = (line[x] + b) & 255
            elif f == 3: line[x] = (line[x] + (a+b)//2) & 255
            elif f == 4:
                p = a + b - c
                pa, pb, pc = abs(p-a), abs(p-b), abs(p-c)
                line[x] = (line[x] + (a if (pa<=pb and pa<=pc) else b if pb<=pc else c)) & 255
        rows.append(bytes(line)); prev = line
    return w, h, [[rows[y][x*4+3] for x in range(w)] for y in range(h)]   # alpha only

def downsample(a, w, h, n):
    out = []
    for oy in range(n):
        y0, y1 = oy*h//n, max((oy+1)*h//n, oy*h//n + 1)
        row = []
        for ox in range(n):
            x0, x1 = ox*w//n, max((ox+1)*w//n, ox*w//n + 1)
            vals = [a[y][x] for y in range(y0, y1) for x in range(x0, x1)]
            row.append(sum(vals)//len(vals))
        out.append(row)
    return out

def main():
    # Accept the .swift source directly: pull out the quoted base64 strings.
    # Falling back to one-per-line keeps plain .b64 files working too, but this
    # means there is no separate extracted copy of the art to keep in sync.
    text = open(sys.argv[1]).read()
    quoted = re.findall(r'"([A-Za-z0-9+/=]{100,})"', text)
    lines = quoted if quoted else [l for l in text.split('\n') if l.strip()]
    frames = []
    for i, l in enumerate(lines):
        try:
            w, h, a = decode_png(l)
        except Exception as e:
            sys.exit(f"frame {i+1}: {e}")
        frames.append(downsample(a, w, h, SIZE))
    n = len(frames)
    stride = (SIZE + 3) // 4          # 4 pixels per byte
    print("// Generated by spark2c.py - do not edit by hand.")
    print("// Claude-spark 'working' animation: %d frames, %dx%d, 2 bits/pixel" % (n, SIZE, SIZE))
    print("// (alpha only - the firmware tints it with the status colour).")
    print("#pragma once")
    print("#include <pgmspace.h>")
    print(f"#define SPARK_FRAMES {n}")
    print(f"#define SPARK_SIZE   {SIZE}")
    print(f"#define SPARK_STRIDE {stride}")
    print(f"const uint8_t SPARK_BITS[{n}][{SIZE}*{stride}] PROGMEM = {{")
    for f in frames:
        print("  {", end="")
        out = []
        for y in range(SIZE):
            for bx in range(stride):
                byte = 0
                for k in range(4):
                    x = bx*4 + k
                    v = f[y][x] if x < SIZE else 0
                    byte |= (min(3, (v*4)//256) & 3) << (6 - 2*k)
                out.append(byte)
        print(",".join(str(b) for b in out), end="")
        print("},")
    print("};")

if __name__ == "__main__":
    main()
